sourcegraph/careers

SWEJOBDESCRIPTION.md
(my vscode plugin also auto formatted the file)
=> Document the interview process

SWEJOBDESCRIPTION.md
added an example about interacting with customers
> You will have the opportunity to interact directly with our customers to help them deploy/configure our software, and solve issues that they encounter.
Clarified some bad practices that we don't do.
=> clarifications

job-descriptions/developer-advocate.md, job-descriptions/product-designer.md, job-descriptions/software-engineer.md
Just proposing a different phrasing that deemphasizes abstract stuff and adds details about or product.
=> Update about the company

README.md, job-descriptions/developer-advocate.md, job-descriptions/growth-biz-ops.md, job-descriptions/product-designer.md
=> Add growth/bizops role

job-descriptions/software-engineer.md
The previous version only mentioned technologies that we use but not problems that we solve. Candidate's also care about the problems they will be working on.
=> Add details about the kinds of problems that we work on

job-descriptions/software-engineer.md
The new job description contains a new set of application questions.
=> Update link to new job description

job-descriptions/software-engineer-intern.md, job-descriptions/software-engineer.md
Remove references to San Francisco.
=> Location is remote

job-descriptions/account-executive.md, job-descriptions/head-of-customer-success.md, job-descriptions/product-manager.md, job-descriptions/software-engineer-backend.md, job-descriptions/software-engineer-code-intelligence.md, job-descriptions/software-engineer-frontend.md, job-descriptions/software-engineer-infrastructure.md, job-descriptions/software-engineer-intern.md, job-descriptions/ux-designer.md
Updating all job descriptions for consistency on:
- About us
- Heading depth
- "Nice-to-have" dashes
- Location
- Interview process questions/reach out
=> Update shared content across job descriptions

.github/CODEOWNERS, README.md, job-descriptions/software-engineer-backend.md, job-descriptions/software-engineer-code-intelligence.md, job-descriptions/software-engineer-frontend.md, job-descriptions/software-engineer-security.md, job-descriptions/software-engineer-template.md
This is one of the new roles that we discussed in our sync 1 week ago.
I have used this as an opportunity to restructure how we do job descriptions, so I am interested in feedback on both the content/description of this new role as well as the format.
=> Add Software Engineer - Security

job-descriptions/customer-engineer.md
FYI @sqs I know today is a busy day, but feel free to deliver feedback on the job req. I'm going to publish it today though so we capture people who click through the news.
=> Add customer engineer

job-descriptions/software-engineer-coding-exercise.md
Small spelling error in your documentation.
=> Spelling error

job-descriptions/ux-designer.md
Some very small changes, I think it would be good to mention that the applicant will be playing a role in developing the culture of design at Sourcegraph.
I also prefer not to specify design tools, as professional designers should be adept at using new tools, and advocating for the best tools.
Once we've agreed and merged let's post to socials!
=> Minor updates to description prior to sharing 

README.md, job-descriptions/account-executive.md, job-descriptions/customer-engineer.md, job-descriptions/demand-generation-manager.md, job-descriptions/product-manager.md, job-descriptions/software-engineer-backend.md, job-descriptions/software-engineer-code-intelligence.md, job-descriptions/software-engineer-distribution.md, job-descriptions/software-engineer-frontend.md, job-descriptions/software-engineer-security.md, job-descriptions/software-engineer-template.md
My editor also auto formatted some of the files that I edited.
=> Move Twitter DM call to action to readme

job-descriptions/software-engineer-security.md
- Clearer expectations and responsibilities
- Add project phase
Post merge:
=> Update security description

README.md, job-descriptions/financial-planning-analysis.md
Draft until the job link has been created in Lever
=> Add FP&A role

README.md, job-descriptions/gtm-sales-operations.md
=> Add GTM (sales) operations role

README.md, job-descriptions/contract-manager.md
@sqs I will create the job listing and add links once you approve the JD here. 
CC @juliasourceress regarding the qualifications and job description for this position—please share any feedback you may have!
(Helpful reference for a similar, but not exactly identical listing from GitLab: https://gitlab.com/gitlab-com/www-gitlab-com/-/blob/master/source/job-families/legal/contract-manager/index.html.md)
=> Add contract manager position; segment job listings into organizational categories

job-descriptions/product-manager.md
Updated interviews PR: https://github.com/sourcegraph/interviews/pull/118
=> Update PM interviews to reflect updated process

README.md, job-descriptions/internal-tools.md
Curious to hear your thoughts on this JD before I publish @sqs
=> Internal tools

job-descriptions/senior-commercial-counsel.md
An applicant DM'd me on Twitter asking if a US law degree is required. I'm not sure. I made this stub PR for you to take over, @dadlerj.
=> counsel: USA law degree required
